### PR TITLE
Add Docker 0.11

### PR DESCRIPTION
**Pull request by sokac**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
All good!

**Comment by ghost** [comment]
For anyone wondering about MAINTAINER: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

**Comment by haxorjim** [comment]
Really? --without-python --without-cpp

**Comment by sokac** [comment]
@haxorjim why would we want to build python/cpp bindings (or any other)? This docker image exposes thrift compiler and nothing else. One can generate python code without python bindings. Note those options were used in 0.10 and 0.9 too.

**Comment by haxorjim** [comment]
I didn't know that. Nevermind then!

**Comment by tylerchr** [comment]
Is there anything I can do to help this PR along? We make use of these very helpful official images, but that means we can't upgrade until this goes through.

**Comment by ghost** [comment]
awesome! thanks for the merge.

**Pull request merged**
