### PR TITLE
Add Docker 0.13

### LINKED ISSUE #21: Thrift 0.13.0 version available
Thrift 0.13.0 version available, can you please make the docker image for it?

### PR DESCRIPTION
**Pull request by yuokada**
Resolve #21

### CODE REVIEW

**Comment by yuokada** [comment]
@ahawkins Could you take a look?

**Review by jeking3 — APPROVED** [review]
The only change from the v0.12.0 Dockerfile was changing it to v0.13.0.  Ship it!

**Comment by sola92** [comment]
Can we merge this? Need 0.13.0

**Comment by hw3jung** [comment]
Would be great to have this merged - thank you!

**Comment by hw3jung** [comment]
@yuokada friendly ping!

**Comment by yuokada** [comment]
Thank you. However, I don't have a permission to merge this.

@ahawkins  Could you please take a look?

**Comment by pavolloffay** [comment]
Any update on this? We would like to use this version in Jaeger project.

@ahawkins can this be merged?

**Comment by Falco20019** [comment]
Ping, we also want to use it in C# Jaeger.

**Comment by pavolloffay** [comment]
Has anybody forked this repository and published image for `0.13`?

**Comment by Falco20019** [comment]
No, only cloned it and built it locally for local usage. Didn't push it anywhere. And looking at how this is already done, I would propose you do the same.

/ping @ahawkins

**Comment by pavolloffay** [comment]
Let's wait till end of the week and if nobody raises hand we should fork this to jaegertracing and publish image there.

**Comment by pavolloffay** [comment]
I have forked the repository to https://github.com/jaegertracing/docker-thrift and published 0.13 image  in https://hub.docker.com/r/jaegertracing/thrift.

**Comment by Falco20019** [comment]
And I thought jaeger could get rid of vendoring thrift since 0.13 finally includes strong named assemblies for C#. Shouldn’t happen ;)

**Comment by yuokada** [comment]
Since the repository have been forked, I will close this pr.

**Pull request closed without merging**
