### PR TITLE
Update README to Copy Generated Files

### PR DESCRIPTION
**Pull request by mcguiremw**

### CODE REVIEW

**Review by jeking3 — CHANGES_REQUESTED** [review]
I posted a better way to use it in my README refresh.  If you set the working directory to /data then `gen-rb` will appear in data, which writes to the directory where the thrift file is.

**Comment by mcguiremw** [comment]
That doesn't bring the generated files down to the host. Which is what `docker cp` does.

**Comment by jeking3** [comment]
Actually, it does:
```
docker run --rm -v "$(pwd):/data" -w "/data" ahawkins/thrift thrift --gen rb service.thrift

    --rm removes the container after it terminates
    -v "$(pwd):/data" mounts the current directory into /data in the container
    -w "/data" sets the working directory in the container to /data

    The generated directory gen-rb is written next to the thrift file in the mounted directory.
```

There's no need for a second command to view or copy the data.

**Comment by mcguiremw** [comment]
Ah, nice.  Thanks.

**Pull request closed without merging**
