### PR TITLE
Bump to version 0.10.0

### PR DESCRIPTION
**Pull request by ahawkins**

### CODE REVIEW

**Comment by ahawkins** [comment]
@tianon next steps?

**Comment by stelcheck** [comment]
Wait, shouldn't this be in a '0.10' directory?

**Comment by tianon** [comment]
Sorry for the delay @ahawkins (and thanks for poking it again to bring it back up in my inbox, @stelcheck :cold_sweat:) -- I think @stelcheck is probably right, unless upstream is not going to have any more 0.9 releases going forward, in which case the 0.9 folder should probably be renamed.

Either way, once you've merged the update, we'll just need a PR against https://github.com/docker-library/official-images/blob/master/library/thrift to get the updated commit reference. :+1:

**Comment by tianon** [comment]
From what I can tell, upstream appears to be in the single-version-track-supported-at-a-time camp (https://archive.apache.org/dist/thrift/ -- back in 2012 they appear to have released 0.7.0 and 0.8.0 simultaneously but haven't done anything similar since), so you could remove the folder entirely if you'd rather, but IMO it makes it a little easier to manage the repo.

**Comment by stelcheck** [comment]
Is there anything I could do to make this happen? Any way I could help?

**Comment by tylerchr** [comment]
I'm also interested in seeing this through. Our build process uses this official image, so we've been waiting for this change to land to recompile all our stuff.

I'm admittedly unfamiliar with how changes here impact the tags available on Docker Hub, but if having both a 0.9 and a 0.10 folder here means that both the `:0.9` and `:0.10` tags are available there then I'd suggest doing that.

**Comment by ahawkins** [comment]
I'll take care of this in the next couple days. Sorry for the delays :(




On Wed, Feb 22, 2017, at 01:13 PM, Tyler Christensen wrote:

> I'm also interested in seeing this through. Our build process uses
> this official image, so we've been waiting for this change to land to
> recompile all our stuff.
> I'm admittedly unfamiliar with how changes here impact the tags
> available on Docker Hub, but if having both a 0.9 and a 0.10 folder
> here means that both the :0.9 and :0.10 tags are available there then
> I'd suggest doing that.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/ahawkins/docker-thrift/pull/5#issuecomment-281593348

**Pull request merged**
